<package format="3">
  <name>orin_rp2_csi</name>
  <version>0.0.1</version>
  <description>Mono and Stereo Camera for Jetson Orin using dual IMX219 RP2 CSI Cameras</description>
  <maintainer email="nathan@vertile.com">Nathan</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>ament_index_cpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
